### ISSUE TITLE
Add Typescript declarations for GEOS functions

### ISSUE THREAD

**Issue by chrispahm** [chrispahm/geos-wasm#12]
I think it would be very helpful to get type hints for the GEOS functions like you'd see in other packages
![image](https://strongloop.com/blog-assets/2016/06/typehint-example-1a.gif)

The [allCFunctions.mjs](https://github.com/chrispahm/geos-wasm/blob/main/src/allCFunctions.mjs) file already includes JSDoc annotations. Unfortunately, I haven't been able to produce a fitting `d.ts` file, maybe someone with more Typescript experience would have an idea what would need to be changed?

**Comment by sanak** [comment]
openlayers[^1] seems to generate types from jsdoc comments with some plugins[^2], but I don't know how to setup the environment... 😅
[^1]: https://github.com/openlayers/openlayers
[^2]: https://github.com/openlayers/jsdoc-plugin-typescript

**Comment by chrispahm** [comment]
<img width="907" alt="image" src="https://github.com/chrispahm/geos-wasm/assets/20703207/617ace6e-42c1-4fcf-b0e0-9983ef4e57f6">

It works in VSCode, haven't gotten it to work in Observable though
