### ISSUE TITLE
Reading/Writing GeoJSON via GEOSCoordSequence_copy(From|To)Buffer may increase performance

### ISSUE THREAD

**Issue by sanak** [chrispahm/geos-wasm#17]
This is just my curiosity, but reading/writing GeoJSON via `GEOSCoordSequence_copy(From|To)Buffer` may increase performance. (I guess that JSON double array to C buffer is faster than JSON to string.)
- [C API Programming | GEOS - #GEOSGeometry](https://libgeos.org/usage/c_api/#geosgeometry)
  ```c
  double coordBuf[] = {1.0,3.0, 2.0,2.0, 3.0,1.0};
  size_t seqSize = 3;
  GEOSCoordSequence* seq = GEOSCoordSeq_copyFromBuffer(
      coordBuf, seqSize, 0, 0);
  
  /* Takes ownership of sequence */
  GEOSGeometry* geom = GEOSGeom_createLineString(seq);
  
  /* Frees all memory */
  GEOSGeom_destroy(geom);
  ```

Shapely seems to use those when GEOS >= 3.10.0.
- `coordseq_from_buffer`: https://github.com/shapely/shapely/blob/70915c9fa1ba8f9c14c68586a62688a52f7a1c7c/src/geos.c#L995
- `coordseq_to_buffer`: https://github.com/shapely/shapely/blob/70915c9fa1ba8f9c14c68586a62688a52f7a1c7c/src/geos.c#L1048

**Comment by chrispahm** [comment]
🎉 published in v1.2.0!
