### ISSUE TITLE
Missing argument for GEOSWKTReader_read in documentation / JSDoc comment / generated types

### ISSUE THREAD

**Issue by mthh** [chrispahm/geos-wasm#31]
Hi and thanks for your work on this library!

The `GEOSWKTReader_read` function accepts two arguments:
- The pointer to the GEOSWKTReader object (a number)
- The WKT string (a string)

However the first argument is missing from the documentation:

https://github.com/chrispahm/geos-wasm/blob/8af73740013b930e0c3ca463e2e2232eb873106d/docs/functions/geos.GEOSWKTReader.md?plain=1#L67-L70

It's also missing from the documentation comments:

https://github.com/chrispahm/geos-wasm/blob/8af73740013b930e0c3ca463e2e2232eb873106d/src/allCFunctions.mjs#L3209-L3217

As such, it's missing from the generated TypeScript types:

![Capture du 2024-03-29 15-28-55](https://github.com/chrispahm/geos-wasm/assets/12172162/a696854d-06cb-48d8-a659-ffb8564198ee)

(which is what I see in my IDE when clicking on the `geos.GEOSWKTReader_read` function in my code)

**Comment by chrispahm** [comment]
Hi @mthh! Thanks a lot for creating this issue and also a PR. I'll try to check within the coming days

**Comment by chrispahm** [comment]
Alright, just published your fix with [v.2.0.0 on npm](https://www.npmjs.com/package/geos-wasm/v/2.0.0)!

**Comment by mthh** [comment]
Thanks for this new release! :+1:

**Comment by chrispahm** [comment]
No worries, thanks for your PR! Note that the release contains the breaking change for the WKT reader (#26), hence the v.2 tag
